include_recipe 'cloudless-box::essentials'
include_recipe 'cloudless-box::packages'
include_recipe 'cloudless-box::webserver'
include_recipe 'cloudless-box::database'
include_recipe 'cloudless-box::firewall'
include_recipe 'cloudless-box::applications'
