---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - 'recipe[cloudless-box::default]'
    attributes:
      cloudless-box:
        gems:
          sass: true

        applications:
          meteor-app:
            layout: meteor
            mongodb: true
            sticky_sessions: true
            repository_path: test/apps/meteor-app
            repository: https://github.com/karolsluszniak/cloudless-box.git

          middleman-app:
            layout: middleman
            ruby: 2.2.2
            repository_path: test/apps/middleman-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
            url:
              - custom-middleman-app-domain-1.com
              - custom-middleman-app-domain-2.com

          node-app:
            layout: node
            bower: true
            repository_path: test/apps/node-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
            env:
              sample_variable: '123'

          phoenix-app:
            layout: phoenix
            postgresql: true
            repository_path: test/apps/phoenix-app
            repository: https://github.com/karolsluszniak/cloudless-box.git

          rails-app:
            layout: rails
            ruby: 2.2.2
            postgresql: true
            redis: true
            repository_path: test/apps/rails-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
            workers:
              invalid: false
              infinite:
                command: 'bundle exec rake infinite'
                scale: 2

          static-app:
            layout: static
            public: ''
            repository_path: test/apps/static-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
            shared_dirs:
              - articles
            symlinks:
              about.html: true
              article_index.html: articles/index.html
              category_index.html: categories/index.html

  - name: phoenix-only
    run_list:
      - 'recipe[cloudless-box::default]'
    attributes:
      cloudless-box:
        applications:
          phoenix-app:
            layout: phoenix
            postgresql: true
            repository_path: test/apps/phoenix-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
