---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - 'recipe[cloudless-box::default]'
    attributes:
      cloudless-box:
        applications:
          node-app:
            layout: node
            bower: true
            repository_path: test/apps/middleman-app

          meteor-app:
            layout: meteor
            mongodb: true
            repository_path: test/apps/meteor-app
            repository: https://github.com/karolsluszniak/cloudless-box.git

          middleman-app:
            layout: middleman
            ruby: 2.2.2
            repository_path: test/apps/middleman-app
            repository: https://github.com/karolsluszniak/cloudless-box.git

          rails-app:
            layout: rails
            ruby: 2.2.2
            postgresql: true
            redis: true
            repository_path: test/apps/rails-app
            repository: https://github.com/karolsluszniak/cloudless-box.git
