name 'cloudless-box'
maintainer 'Karol Słuszniak'
maintainer_email 'karol@cloudless.pl'
license 'all_rights'
description 'Installs/Configures Cloudless box'
long_description 'Installs/Configures Cloudless box capable of running multiple web applications'
version '0.1.0'

depends 'build-essential', '~> 2.2.3'
depends 'database', '~> 4.0.8'
depends 'git', '~> 4.3.3'
depends 'imagemagick', '~> 0.2.3'
depends 'iptables', '~> 1.0.0'
depends 'ssh_known_hosts', '~> 2.0.0'
depends 'nginx', '~> 2.7.6'
depends 'nodejs', '~> 2.4.0'
depends 'ntp', '~> 1.8.6'
depends 'postgresql', '~> 3.4.20'
depends 'rbenv', '~> 1.7.1'
depends 'selinux', '~> 0.9.0'
depends 'yum', '~> 3.6.3'
depends 'yum-epel', '~> 0.6.2'

